# Generated by Django 3.2.3 on 2021-05-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=72, null=True, verbose_name='Sobrenome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='clients', verbose_name='Fotos')),
                ('dt_birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Doc id')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descricao')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preco')),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='taxas')),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=10, unique=True, verbose_name='Numero do vendedor')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
                ('products', models.ManyToManyField(blank=True, null=True, to='core.Product')),
            ],
            options={
                'verbose_name': 'Vendedor',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='doc_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.id'),
        ),
    ]
