# Generated by Django 3.2.3 on 2021-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sale_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Fotos'),
        ),
    ]
