name: Formating test

on: [push, pull_request]

jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: [3.8]
  steps:
  - name: 'Checking the black format'
  - uses: RojerGS/python-black-check@master
  - with:
      line-length: '79'
      path: '.'
      include: '/(client|core)/'
      exclude: '(/*.html|/*.mo|/*.po|/*.png|/*.rst)'
    