name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      - job1:
        - name: Run black
          run: |
          black --exclude "/(\.git|\.venv|venv|\.txt|\.md|\.html)/" --check clients/settings.py clients/urls.py core/urls.py core/tests.py core/models.py core/views.py

      - job2:
        needs: job1
        - name: Run Tests
          run: |
            python manage.py test
